# Generated by Django 4.1.4 on 2022-12-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="image",
            name="total_likes",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
